version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQATestRajni2903Project
  gitServerName: rajniVCTest
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SSL_JDBC_Test
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/prabhakarsag
  gitUsername: rimabarman
  gitBranch: main
- name: JMS2waySSL
  gitServerName: rimaSCName
  gitUrl: https://github.com/prabhakarsag
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqatestrajni2903.integrations:refdatatest
  packages:
  - name: SIQATestRajni2903Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.siqatestrajni2903.referencedata:refdata
  packages:
  - name: SIQATestRajni2903Project
    version: "1.0"
  - name: JMS2waySSL
    version: "1.0"
  - name: SSL_JDBC_Test
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
